# -*- coding: utf-8 -*-
"""Carte_interactive_CarHab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AbToFAjmLr-Qh8XD4I_G4hB4tXPwX_SE

# Contexte

**Contexte :**  Dans le cadre du projet Vivescia, il faut étudier les impacts des aménagements agricoles et les élements du paysage sur la biodiversité. La carte intéractive met en évidence les milieux naturels et semi-naturels du territoire de Beauvais, ainsi que les parcelles agricoles. Cet outil permet également d'avoir des informations comme la surface des milieux présents sur le territoire pouvant servir d'indicateur pour évaluer l'impact.

# Traitement des données
"""

#Utilisation de la bibliothèque geopandas pour charger les fichiers geojson et gpkg et ensuite les convertir
import geopandas as gpd

# Charger la couche des communes de l'Oise issu de la source : https://france-geojson.gregoiredavid.fr/
communes = gpd.read_file("/content/communes-60-oise.geojson")
communes

"""1) Traitement de la couche département Oise pour avoir seulement la commune de Beauvais"""

#Filtre sur la commune de Beauvais dont le code INSEE = 60057
BVS = communes[communes["code"] == "60057"]  #On cherche dans le fichier des communes de l'Oise, la ligne pour laquelle le champ "code" contient "60057"
BVS.head()

"""2. Import et conversion de .GPKG en .geoJSON de la couche des milieux naturels et semi-naturels issu de Carhab pour le département de l'Oise (60) pour avoir le même format que le fichier de Beauvais"""

#Visualisation des couches de CarHab de l'Oise
!pip install fiona
import fiona
layers = fiona.listlayers("/content/CarHab_60_Oise_Habitats_CarHab.gpkg")

print("Couches de CarHab de l'Oise :", layers)

#Import données CarHab60.gpkg
import geopandas as gpd
carhab60 = gpd.read_file("/content/CarHab_60_Oise_Habitats_CarHab.gpkg", layer="habitats_carhab")
carhab60.head()

#convertir CarHab60.gpkg en GeoJSON
carhab60.to_file("/content/carhab60.geojson", layer="habitats_carhab", driver="geojson")
carhab60

#Visualisation des coordonnées géographiques des fichiers
print(BVS.crs)
print(carhab60.crs)

#Mettre au même coordonnées géographique
carhab60 = carhab60.to_crs(4326)

#Intersection de la couche carhab60 (milieux naturels et semi-naturels) avec la commune de Beauvais
beauvais_hab_test = gpd.clip(carhab60, BVS, keep_geom_type=True, sort=False)
beauvais_hab_test

#Création fichier au format geoJSON
beauvais_hab_test.to_file("beauvais_hab_test.geojson", driver="GeoJSON")

"""# Visualisation des données du dataframe

"""

#Import des données traitées sur QGIS issu du lien https://geoservices.ign.fr/habitats-carhab
beauvais_hab = gpd.read_file('/content/beauvais_hab_test.geojson')

#Import des bibliothèque
!pip install matplotlib #utilisation de matplotlib
!pip install mapclassify
import geopandas as gpd
import matplotlib.pyplot as plt
import folium
from branca.colormap import ColorMap
from folium import plugins
from folium import LayerControl
from google.colab import files

#Visualisation de la tête du dataFrame
beauvais_hab.head()

#Visualisation des colonnes et des types de données
beauvais_hab.info()

#Création de la carte intéractive
m = beauvais_hab.explore(column ="nom_physio",
                     cmap = ("Yellow","Green","Green","Green","#006400","#006400","#90EE90","#90EE90","#90EE90","#1E90FF","#20B2AA","#20B2AA","#FFD700","#ff7f00"),#végétation haute mise en orange pour le visualiser plus rapidement
                     tooltip = ["nom_simplifie_hab","occupation","milieu","surface"],
                     tooltip_kwds = dict(aliases = ["type habitat", "occupation","milieu","Surface (m²)"]),
                     popup = ["nom_physio","nom_simplifie_hab","nom_complet_hab","occupation","milieu","surface"], #affiche l'ensemble des champs sur une fenêtre fixe
                     popup_kwds = dict(aliases = ["Type biotope","Type habitat","Nom complet habitation","occupation", "milieu","Surface du polygone (m²)"]),
                     style_kwds = dict(color = "black"),
                     name = "cartes habitats naturels beauvais 2024",
                     legend = True,
                     legend_kwds={'caption': "Type d'habitat naturel et semi-naturel"},

                    )
#Ajout d'une mini-carte
mini_map = plugins.MiniMap()
m.add_child(mini_map)

#Ajout d'un bouton pour voir les couches
folium.LayerControl().add_to(m)
m

#Enregistrement de la carte intéractive au format html
m.save("Carte_Hab_Bvs2024.html")
files.download("Carte_Hab_Bvs2024.html")